version: '2'
services:
  fullstack-nginx:
    build:
      context: ./.docker/nginx
    container_name: fullstack-nginx
    links:
      - fullstack-node
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/usr/share/nginx/html
  fullstack-node:
    build:
      context: ./.docker/node
    container_name: fullstack-node
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: "yarn start"
    